# Generated by Django 2.2.7 on 2019-11-24 12:47

import cf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tags', cf.models.TagFeild(max_length=200)),
                ('dif', models.IntegerField(default=0)),
            ],
        ),
    ]
