# Generated by Django 2.2.7 on 2019-11-25 10:38

import cf.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='my_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=cf.models.TagFeild(max_length=200),
        ),
    ]
