# Generated by Django 2.2.7 on 2019-11-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0002_auto_20191125_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='my_id',
        ),
    ]
