# Generated by Django 2.2.7 on 2019-11-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0003_remove_problem_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='my_id',
            field=models.IntegerField(default=0),
        ),
    ]
