# Generated by Django 2.2.7 on 2019-11-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0004_problem_my_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='my_id',
        ),
    ]
