# Generated by Django 2.2.7 on 2019-11-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0006_problem_my_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
