# Generated by Django 2.2.7 on 2019-11-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0007_problem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='problem_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('time_lim', models.CharField(max_length=200)),
                ('mem_lim', models.CharField(max_length=200)),
                ('in_file', models.CharField(max_length=200)),
                ('out_file', models.CharField(max_length=20)),
                ('text', models.TextField()),
            ],
        ),
    ]
