# Generated by Django 2.2.7 on 2019-12-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0010_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
