# Generated by Django 3.0 on 2020-01-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cf', '0011_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_problem_status',
            name='memory',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_problem_status',
            name='time',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
